version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: niki-postgres
    environment:
      POSTGRES_DB: nikidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - niki-pgdata:/var/lib/postgresql/data

  niki-bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  niki-pgdata:
